openapi: 3.0.3
info:
  title: 2023-BBE-1-G1_HotelResources API
  version: '1.0'
  description: The 2023-BBE-1-G1_HotelResources API. Credentials → manager Manager1234
servers:
  - url: '/'
    description: Localhost

paths:
  /hotels/hotel:
    $ref: 'api/Hotel.yml#/default'
  /hotels/hotel/search:
    $ref: 'api/Hotel.yml#/search'

  /rooms/room:
    $ref: 'api/Room.yml#/default'
  /rooms/room/search:
    $ref: 'api/Room.yml#/search'

  /test:
    $ref: 'api/Test.yml#/test'

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

security:
  - BasicAuth: []
