openapi: 3.0.3
info:
  title: 2023-BBE-1-G1_HotelResources API
  version: '1.0'
  description: |
    The 2023-BBE-1-G1_HotelResources API. 
    Credentials:
      Manager → manager Manager1234 |
      Client → pedro_romero Pedro123
servers:
  - url: '/'
    description: Localhost

paths:
  /hotels/hotel:
    $ref: 'api/Hotel.yml#/default'
  /hotels/hotel/search:
    $ref: 'api/Hotel.yml#/search'

  /rooms/room:
    $ref: 'api/Room.yml#/default'
  /rooms/room/search:
    $ref: 'api/Room.yml#/search'

  /bookings/booking:
    $ref: 'api/Booking.yml#/default'
  /bookings/booking/search:
    $ref: 'api/Booking.yml#/search'

  /users/signup:
    $ref: 'api/User.yml#/signup'

  /employees/employee:
    $ref: 'api/Employees.yml#/default'
  /test:
    $ref: 'api/Test.yml#/test'

  /shifts/shift:
    $ref: 'api/Shift.yml#/default'
  /shifts/shift/search:
    $ref: 'api/Shift.yml#/search'

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []
